const { generateUUID, signJwt }=require('../../utils/crypto');const config=require('../../config');const {recordAudit}=require('../../utils/audit');const ledger=require('../ledger/engine');
class ContentService{
 constructor(){this.posts=new Map();this.mediaAssets=new Map();this.purchasedPPV=new Set();}
 createPost({creatorId,textContent,visibility='SUBSCRIBERS_ONLY',isPPV=false,ppvPriceCents=0,compliance2257Id}){if(isPPV&&(ppvPriceCents<=0||ppvPriceCents>config.MAX_PPV_PRICE_CENTS))throw new Error('Invalid PPV price.');const p={id:generateUUID(),creatorId,textContent,visibility,isPPV,ppvPriceCents:isPPV?ppvPriceCents:0,compliance2257Id:compliance2257Id||null,mediaAssets:[],likesCount:0,commentsCount:0,createdAt:new Date().toISOString()};this.posts.set(p.id,p);recordAudit({actorUserId:creatorId,actorRole:'CREATOR',action:'CREATE_POST',resourceType:'POST',resourceId:p.id});return p;}
 attachMedia({postId,creatorId,mediaType,originalFileName,durationSeconds=0}){const id=generateUUID();const a={id,postId,creatorId,mediaType,originalFileName,storageKey:`media/vault/${creatorId}/${id}.m3u8`,thumbnailUrl:`https://cdn.creatoros.com/thumbs/${id}.jpg`,durationSeconds,isLocked:true,createdAt:new Date().toISOString()};this.mediaAssets.set(id,a);const p=this.posts.get(postId);if(p)p.mediaAssets.push(a);return a;}
 getFeed({userId,isSubscriberOfCreator=false}){return [...this.posts.values()].map(p=>{const purchased=this.purchasedPPV.has(`${userId}:${p.id}`);const access=p.creatorId===userId||purchased||(!p.isPPV&&(p.visibility==='PUBLIC'||isSubscriberOfCreator));return {...p,hasPurchased:purchased,canAccess:access,mediaAssets:p.mediaAssets.map(a=>({...a,isLocked:!access,playbackUrl:access?`https://stream.creatoros.com/hls/${a.id}.m3u8?token=${signJwt({mediaId:a.id,userId},config.JWT_SECRET,300)}`:null}))};}).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));}
 purchasePPV({userId,postId,idempotencyKey}){const p=this.posts.get(postId);if(!p)throw new Error('Post not found.');if(!p.isPPV)throw new Error('This post is not a PPV post.');const key=`${userId}:${postId}`;if(this.purchasedPPV.has(key))return {success:true,message:'Already unlocked.'};const wallet=ledger.getOrCreateUserWallet(userId), creator=ledger.getOrCreateCreatorPayable(p.creatorId), platform=ledger.getSystemAccount('REVENUE_PLATFORM_PPV_FEE');const fee=Math.round(p.ppvPriceCents*config.PLATFORM_FEE_BPS/10000);ledger.recordTransaction({idempotencyKey,entryType:'PPV_PURCHASE',referenceEntityType:'POST',referenceEntityId:postId,description:`PPV unlock for post ${postId}`,legs:[{accountId:wallet.id,amountCents:-p.ppvPriceCents},{accountId:creator.id,amountCents:p.ppvPriceCents-fee},{accountId:platform.id,amountCents:fee}],actorUserId:userId});this.purchasedPPV.add(key);return {success:true,unlocked:true,priceCents:p.ppvPriceCents};}
}
module.exports=new ContentService();
