-- Migration 001: Identity, Users, Sessions, and MFA
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TYPE user_role AS ENUM ('FAN', 'CREATOR', 'MODERATOR', 'ADMIN', 'SYSTEM');
CREATE TYPE account_status AS ENUM ('PENDING_VERIFICATION', 'ACTIVE', 'SUSPENDED', 'BANNED', 'DELETED');
CREATE TABLE users (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), email VARCHAR(255) UNIQUE NOT NULL, password_hash VARCHAR(255) NOT NULL, username VARCHAR(50) UNIQUE NOT NULL, display_name VARCHAR(100) NOT NULL, avatar_url TEXT, bio TEXT, role user_role NOT NULL DEFAULT 'FAN', status account_status NOT NULL DEFAULT 'PENDING_VERIFICATION', is_18_plus_declared BOOLEAN NOT NULL DEFAULT FALSE, is_age_verified BOOLEAN NOT NULL DEFAULT FALSE, age_verified_at TIMESTAMPTZ, failed_login_attempts INT NOT NULL DEFAULT 0, lockout_until TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE user_identities_vault (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), user_id UUID UNIQUE NOT NULL REFERENCES users(id) ON DELETE RESTRICT, legal_first_name_encrypted BYTEA NOT NULL, legal_last_name_encrypted BYTEA NOT NULL, date_of_birth DATE NOT NULL, id_document_type VARCHAR(50) NOT NULL, id_document_country VARCHAR(3) NOT NULL, id_document_hash VARCHAR(128) NOT NULL, verification_provider VARCHAR(50) NOT NULL, verification_reference_id VARCHAR(100) NOT NULL, verified_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE sessions (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, refresh_token_hash VARCHAR(128) NOT NULL UNIQUE, refresh_token_family UUID NOT NULL DEFAULT uuid_generate_v4(), device_fingerprint VARCHAR(128) NOT NULL, user_agent TEXT, ip_address INET, is_revoked BOOLEAN NOT NULL DEFAULT FALSE, expires_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE mfa_devices (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, device_type VARCHAR(30) NOT NULL, secret_encrypted BYTEA NOT NULL, name VARCHAR(100) NOT NULL, is_confirmed BOOLEAN NOT NULL DEFAULT FALSE, last_used_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX idx_users_email ON users(email); CREATE INDEX idx_users_username ON users(username); CREATE INDEX idx_sessions_user_id ON sessions(user_id); CREATE INDEX idx_sessions_family ON sessions(refresh_token_family);
