-- Migration 004: Subscriptions, PPV purchases, and digital marketplace
CREATE TYPE subscription_status AS ENUM ('ACTIVE','PAST_DUE','CANCELED','EXPIRED');
CREATE TYPE order_status AS ENUM ('PENDING_ACCEPTANCE','IN_PROGRESS','DELIVERED','REVISION_REQUESTED','COMPLETED','DISPUTED','REFUNDED');
CREATE TYPE service_category AS ENUM ('DIGITAL_ART','VIDEO_EDITING','VOICE_WORK','COSPLAY_DESIGN','CUSTOM_AUDIO');
CREATE TABLE subscription_tiers (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),creator_id UUID NOT NULL REFERENCES creator_profiles(id) ON DELETE CASCADE,tier_level INT NOT NULL DEFAULT 1,name VARCHAR(100) NOT NULL,description TEXT,price_cents BIGINT NOT NULL CHECK(price_cents>=100),is_active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE subscriptions (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,creator_id UUID NOT NULL REFERENCES creator_profiles(id) ON DELETE RESTRICT,tier_id UUID NOT NULL REFERENCES subscription_tiers(id) ON DELETE RESTRICT,status subscription_status NOT NULL DEFAULT 'ACTIVE',current_period_start TIMESTAMPTZ NOT NULL,current_period_end TIMESTAMPTZ NOT NULL,cancel_at_period_end BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(user_id,creator_id));
CREATE TABLE ppv_purchases (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,post_id UUID NOT NULL REFERENCES content_posts(id) ON DELETE RESTRICT,amount_paid_cents BIGINT NOT NULL CHECK(amount_paid_cents>=0),unlocked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(user_id,post_id));
CREATE TABLE service_listings (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),creator_id UUID NOT NULL REFERENCES creator_profiles(id) ON DELETE CASCADE,title VARCHAR(200) NOT NULL,description TEXT NOT NULL,category service_category NOT NULL,base_price_cents BIGINT NOT NULL CHECK(base_price_cents>=500),delivery_days INT NOT NULL CHECK(delivery_days>=1),revision_limit INT NOT NULL DEFAULT 2,is_approved_by_safety BOOLEAN NOT NULL DEFAULT FALSE,is_active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE service_orders (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),listing_id UUID NOT NULL REFERENCES service_listings(id) ON DELETE RESTRICT,buyer_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,creator_id UUID NOT NULL REFERENCES creator_profiles(id) ON DELETE RESTRICT,order_status order_status NOT NULL DEFAULT 'PENDING_ACCEPTANCE',agreed_price_cents BIGINT NOT NULL CHECK(agreed_price_cents>=500),escrow_held_cents BIGINT NOT NULL CHECK(escrow_held_cents>=0),requirements_text TEXT NOT NULL,delivery_attachment_url TEXT,deadline_at TIMESTAMPTZ NOT NULL,completed_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
