-- Migration 006: Live streaming, messaging, moderation, and audit
CREATE TYPE stream_status AS ENUM ('IDLE','LIVE','DISCONNECTED','ENDED');
CREATE TYPE moderation_severity AS ENUM ('LOW','MEDIUM','HIGH','CRITICAL_LEGAL');
CREATE TYPE moderation_action AS ENUM ('NONE','WARNING','CONTENT_TAKEDOWN','ACCOUNT_SUSPENDED','PERMANENT_BAN','LEGAL_ESCALATION');
CREATE TABLE live_rooms (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),creator_id UUID NOT NULL REFERENCES creator_profiles(id) ON DELETE CASCADE,title VARCHAR(200) NOT NULL,stream_key_hash VARCHAR(128) NOT NULL,status stream_status NOT NULL DEFAULT 'IDLE',viewer_count INT NOT NULL DEFAULT 0,peak_viewer_count INT NOT NULL DEFAULT 0,total_tips_cents BIGINT NOT NULL DEFAULT 0,compliance_2257_id UUID REFERENCES performer_records_2257(id),started_at TIMESTAMPTZ,ended_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE conversations (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),participant_a_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,participant_b_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,last_message_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE messages (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,sender_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,text_content TEXT,is_ppv BOOLEAN NOT NULL DEFAULT FALSE,price_cents BIGINT DEFAULT 0,is_unlocked BOOLEAN NOT NULL DEFAULT FALSE,attachment_media_id UUID REFERENCES media_assets(id),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE moderation_cases (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),target_entity_type VARCHAR(50) NOT NULL,target_entity_id UUID NOT NULL,reporter_user_id UUID REFERENCES users(id),severity moderation_severity NOT NULL DEFAULT 'LOW',reason_code VARCHAR(100) NOT NULL,status VARCHAR(50) NOT NULL DEFAULT 'QUEUED',assigned_moderator_id UUID REFERENCES users(id),action_taken moderation_action NOT NULL DEFAULT 'NONE',ai_risk_score NUMERIC(5,4),ai_rationale JSONB,resolved_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE audit_logs (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),actor_user_id UUID REFERENCES users(id),actor_role user_role NOT NULL,action VARCHAR(100) NOT NULL,resource_type VARCHAR(50) NOT NULL,resource_id VARCHAR(100) NOT NULL,ip_address INET,user_agent TEXT,previous_state JSONB,new_state JSONB,rationale TEXT,timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW());
